### ISSUE TITLE
Use jablon with Raspi

### ISSUE THREAD

**Issue by EIKSEU** [tomvit/ja2mqtt#4]
Hello,

I want to use jablon with my Rasperry pi.

I cloned jablon and then ran venv-create.sh and env.sh. 2 folders were created jablon/venv and jablon/bin/venv
but how can I start the program now?

Thanks

**Comment by tomvit** [comment]
Please delete `venv` directories you created and run the following steps:

1. Go to the `jablon` root directory where you cloned the repo.
2. run `bin/create-venv.sh`. This should create the virtual environment folder and install all requirements from `requirements.txt`
3. Go to the bin sub-directory and run `source env.sh`. This will create environment varialbes required by jablon.

Please note that this library currently only provides terminal emulator. The REST API for Jablotron is not yet implemented but I have it on my TODO list as will need it too.
